### ISSUE TITLE
Feedback on week 9 project progress

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-2/main#37]
Subject: feedback on week 9 project progress

See [v1.2 progress guide](https://nuscs2113-ay1819s1.github.io/website/admin/project-w09-v12.html) for more details of the activities mentioned below.

### Leftovers from v1.1

- [x]  Auto-publishing set up for the team repo and the website is available at [link](https://CS2113-AY1819S1-W12-2.github.io/main) (:heavy_check_mark: well done!)
* README page:
  -  [x]  Some parts not related to your product are removed (:heavy_check_mark: well done!)
  -  [ ]  se-edu/addressbook-level[3/4] acknowledged (:exclamation: try to do by next milestone)
  -  [ ]  `Ui.png` has been updated (:exclamation: try to do by next milestone)

### Recommended progress for v1.2

- [x]  Issue labels set up e.g., `type.*`, `priority.*` (:heavy_check_mark: well done!)
- [x]  Milestones created: v1.2 v1.3 v1.4 [Please ensure milestones are setup until 'v1.4'] (:heavy_check_mark: well done!)
- [x]  Some issues marked as `type.Story` e.g., [link](https://github.com/CS2113-AY1819S1-W12-2/main/issues/6) (:heavy_check_mark: well done!)
- [x]  Some issues prioritized using `priority.*` labels e.g., [link](https://github.com/CS2113-AY1819S1-W12-2/main/issues/6) (:heavy_check_mark: well done!)
*  Milestone v1.2 _managed_ systematically
   -  [ ]  A suitable deadline set (:exclamation: try to do by next milestone)
   -  [x]  Issues allocated to v1.2 e.g., [link](https://github.com/CS2113-AY1819S1-W12-2/main/issues/8) (:heavy_check_mark: well done!)
   -  [x]  All issues/PRs in it are closed/merged. (:heavy_check_mark: well done!)
   -  [ ]  Milestone closed  (:exclamation: try to do by next milestone)
   -  [x]  Code tagged as `v1.2`  (:heavy_check_mark: well done!)
- [x]  Build passing (:heavy_check_mark: well done!)
-  [x]  Some issues assigned to milestone v1.3 e.g., [link](https://github.com/CS2113-AY1819S1-W12-2/main/issues/5) (:heavy_check_mark: well done!)

Not graded:
- [x] Updated User Guide for v1.2  (:+1:  Kudos!)

### Leftovers from v1.1

* Used forking workflow:
   - [x]  Forked team repo (:heavy_check_mark: well done!)
   - [x]  Created PRs [link](https://github.com/CS2113-AY1819S1-W12-2/main/pull/32) (:heavy_check_mark: well done!)
   - [ ]  Gave review comments to other PRs (:exclamation: try to do by next milestone)
- [ ]  Merged updates to documents (:exclamation: try to do by next milestone)
- [x]  `bearperson1.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [ ]  Merged updates to the Developer Guide (:exclamation: try to do by next milestone)
  - [ ]  Has issues/PRs assigned for the next milestone (:exclamation: try to do by next milestone)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [ ]  Merged updates to the Developer Guide (:exclamation: try to do by next milestone)
  - [ ]  Has issues/PRs assigned for the next milestone (:exclamation: try to do by next milestone)

### Leftovers from v1.1

* Used forking workflow:
   - [x]  Forked team repo (:heavy_check_mark: well done!)
   - [x]  Created PRs [link](https://github.com/CS2113-AY1819S1-W12-2/main/pull/1) (:heavy_check_mark: well done!)
   - [ ]  Gave review comments to other PRs (:exclamation: try to do by next milestone)
- [x]  Merged updates to documents (:heavy_check_mark: well done!)
- [x]  `e0201942.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [ ]  Has issues/PRs assigned for the next milestone (:exclamation: try to do by next milestone)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the next milestone (:heavy_check_mark: well done!)

Tutor: @okkhoy

Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2018-10-17 02:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.
